version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"                        # root
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5           # limit the number of PRs open simultaneously
    labels:
      - dependencies

  - package-ecosystem: "gradle"
    directory: "/sample"                  # sample
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - dependencies
